//
//  CarBrand.swift
//  CarsInventory
//
//  Created by Roman on 2025-01-06.
//

import Foundation


enum CarBrandOld: String, CaseIterable, Hashable, Identifiable, Codable {
    var displayName: String {
        rawValue
    }

    var id: String {
        rawValue
    }

    // A
    case abarth = "ABARTH"
    case abt = "ABT"
    case ac = "AC"
    case acSchnitzer = "AC SCHNITZER"
    case acura = "ACURA"
    case alfaRomeo = "ALFA-ROMEO"
    case allard = "ALLARD"
    case alpina = "ALPINA"
    case alpine = "ALPINE"
    case alvis = "ALVIS"
    case amg = "AMG"
    case arden = "ARDEN"
    case ariel = "ARIEL"
    case ascari = "ASCARI"
    case astonMartin = "ASTON MARTIN"
    case auburn = "AUBURN"
    case audi = "AUDI"
    case austingHealey = "AUSTIN-HEALEY"
    case autoUnion = "AUTO UNION"
    case artega = "ARTEGA"
    case apollo = "APOLLO"
    case aac = "AAC"
    case abd = "ABD"
    case adrenaline = "ADRENALINE"
    case aeon = "AEON"
    case alanMann = "ALAN MANN"
    case alba = "ALBA"
    case americanMotors = "AMERICAN MOTORS"
    case amilcar = "AMILCAR"
    case ark = "ARK"
    case arash = "ARASH"
    case asc = "ASC"
    case asl = "ASL"
    case asma = "ASMA"
    case ats = "ATS"
    case austin = "AUSTIN"
    case autech = "AUTECH"
    
    // B
    case bac = "BAC"
    case baldwinMotion = "BALDWIN MOTION"
    case betone = "BERTONE"
    case ballot = "BALLOT"
    case bentley = "BENTLEY"
    case benz = "BENZ"
    case bizzarrini = "BIZZARRINI"
    case bmw = "BMW"
    case brabus = "BRABUS"
    case bugatti = "BUGATTI"
    case buick = "BUICK"
    
    // C
    case cadillac = "CADILLAC"
//    "CALLAWAY",
//    "CARLSSON",
//    "CATERHAM",
    case chevrolet = "CHEVROLET"
    case chrysler = "CHRYSLER"
//    "CITROËN",
//    "CISITALIA",
//    "CHEVRON",
//    "CASTAGNA",
//    "CIZETA",
//    "CAPARO",
//    "CONTINENTAL",
//    "COOPER",
//    "CORD",
//    "CORVAIR",
//    "COURAGE",
    
    // D
//    "DAIMLER",
    case datsun = "DATSUN"
//    "DAUER",
//    "DELAGE",
//    "DELAHAYE",
//    "DETOMASO",
//    "DINO",
    case dodge = "DODGE"
//    "DOME",
//    "DONKERVOORT",
//    "DUESENBERG",
//    "DACIA",
//    "DAEWOO",
//    "DAIHATSU",
//    "DE DION-BOUTON",
//    "DELAUNAY",
//    "DELOREAN",
//    "DENZEL",
//    "DERBY",
//    "DESOTO",
//    "DETROIT ELECTRIC",
//    "DEVIN",
//    "DEVON",
//    "DIATTO",
//    "DINAN",
//    "DKW",
//    "DORAN",
//    "DP",
//    "DREKER",
//    "DUAL-GHIA",
//    "DUPONT",
//    "DAVID BROWN",
//    "DEVEL SIXTEEN",
    
    // E
//    "EDAG",
//    "EDO",
//    "EDWARDS",
//    "ELFIN",
//    "ELVA",
//    "EAGLE",
//    "ECHIDNA",
//    "EMME",
//    "ENIZIO",
//    "EPSILON",
//    "ERMINI",
//    "ETUD",
//    "EUNOS",
//    "EVANS",
//    "EVOLVE",
//    "EXAGON",
//    "ELEMENTAL",
    
    // F
    case ferrari = "FERRARI"
    case fiat = "FIAT"
//    "FIORAVANTI",
//    "FISKER",
    case ford = "FORD"
//    "FABCAR",
//    "FACEL VEGA",
//    "9FF",
//    "FARADAY",
//    "FIFTEEN52",
//    "FLAJOLE",
//    "FOOSE",
//    "FORCED FED",
//    "FACETTI",
//    "FACTORY FIVE",
//    "FARALLI & MAZZ..",
//    "FARBIO",
//    "FARMAN",
//    "FARBOUD",
//    "FENIX",
//    "FAB DESIGN",
//    "FENOMENON",
//    "FRAZER NASH",
//    "FRONTY",
//    "F.R.P",
//    "FSWERKS",
//    "FUORE",
    
    // G
//    "GALPIN",
//    "GEIGER",
//    "GEMBALLA",
//    "GHIA",
//    "GINETTA",
//    "GENERAL MOTORS",
//    "GORDINI",
//    "GORDON MURRAY"
//    "GPOWER",
//    "GREENWOOD",
//    "GRMN",
//    "GUMPERT",
//    "GAACO",
//    "GEELY",
//    "GENADDI",
//    "GIGLIATO",
//    "GILLET",
//    "GIUGIARO",
//    "GLASSPAR",
//    "GRABER CARS",
//    "GREDDY",
//    "GTA",
//    "GENESIS",
//    "GILLET",
    case gmc = "GMC"
    
    // H
//    "HAMANN",
//    "HARTGE",
//    "HENNESSEY",
//    "HISPANO-SUIZA",
//    "HOLDEN",
    case honda = "HONDA"
//    "HOMMEL",
//    "HORCH",
//    "HPD",
//    "HSV",
//    "HURST",
//    "HONGQI",
//    "HAFEI",
//    "HASPORT",
//    "HBH",
//    "HEYNSDYK",
//    "HKS",
//    "HUNTER",
//    "HOERMANN",
//    "HOOPER",
//    "HOTCHKISS",
//    "HOWELL",
//    "HRG",
//    "HUDSON",
//    "HULME",
    case hyindai = "HYUNDAI"
//    "HEULIEZ",
    
    // I
//    "IMPERIAL",
    case infinity = "INFINITI"
//    "INNOTECH",
//    "ISDERA",
//    "ISO",
//    "ISOTTA",
    case isuzu = "ISUZU"
//    "ITALDESIGN",
//    "I.DE.A",
//    "IED",
//    "IMOLA RACING",
//    "IMPUL",
//    "IMSA",
//    "INTERMECCANICA",
//    "INTREPID",
//    "INVICTA",
//    "ICENI",
//    "ICONA",
//    "ICONIC",
//    "ITALMECCANICA",
    
    // J
    case jaguar = "JAGUAR"
    case jeep = "JEEP"
//    "JENSEN",
//    "JAVAN",
//    "JETSTREAM",
//    "JIMENEZ",
//    "JIOTTO",
//    "JOEST",
//    "JBA",
//    "JAC",
    
    // K
//    "KAISER-DARRIN",
//    "KARMANN",
//    "KATECH",
//    "KEATING",
//    "KELLISON",
//    "KEPLER MOTORS",
    case kia = "KIA"
//    "KICHERER",
//    "KLEEMANN",
    case koenigsegg = "KOENIGSEGG"
//    "KOENIG-SPECIALS",
//    "KREMER",
//    "KTM",
//    "KURTIS",
//    "KARMA",
    
    // L
//    "LAGONDA",
    case lamborghini = "LAMBORGHINI"
    case lancia = "LANCIA"
    case lexus = "LEXUS"
    case lincoln = "LINCOLN"
//    "LINGENFELTER",
//    "LISTER",
    case lola = "LOLA"
    case lotus = "LOTUS"
//    "LABORATORIO",
//    "LANCHESTER",
    case landRover = "LAND ROVER"
//    "LANG-COOPER",
//    "LARAKI",
//    "LASALLE",
//    "Laurin & Klement",
//    "LEA FRANCIS",
//    "LEBLANC",
//    "LIGHTNING",
//    "LIGIER",
//    "LJ GARCIA",
//    "LOCAL MOTORS",
//    "LOCOMOBILE",
//    "LOCUS",
//    "LODER1899",
//    "LOHNER-PORSCHE",
//    "LOREMO",
//    "LORRAINE DIE..",
//    "LOTEC",
//    "LUMMA,",
//    "LYKAN",
//    "LLOYD",
//    "LOBINI",
    case lucid = "LUCID"
//    "LUXGEN",
    
    // M
//    "MAGNA",
//    "MALLETT",
//    "MAMEROW",
//    "MANSORY",
//    "MARCH",
//    "MARCOS",
//    "MARMON",
//    "MARUSSIA",
//    "MASERATI",
//    "MASTRETTA",
//    "MATECH-FORD",
//    "MATRA-SIMCA",
//    "MAYBACH",
//    "MAZDA",
//    "MAZEL",
//    "MAZZANTI",
//    "MCA",
//    "MCCULLOCH",
//    "MCLAREN",
//    "MCV",
//    "MEGA",
//    "MELKUS",
//    "MELLING",
    case mercedes = "MERCEDES"
    case mercedesAMG = "MERCEDES-AMG"
    case mercedesBenz = "MERCEDES-BENZ"
    case mercedesKnight = "MERCEDES-KNIGHT"
//    "MERCER",
    case mercury = "MERCURY"
    case mg = "MG"
//    "MILLER",
//    "MINERVA",
    case mini = "MINI"
//    "MIRAGE",
    case mitubishi = "MITSUBISHI"
//    "MITSUOKA",
//    "MOBSTEEL",
//    "MOMO",
//    "MONTEVERDI",
//    "MOONCRAFT",
//    "MORETTI",
//    "MORGAN",
//    "MORRIS",
//    "MOSLER",
//    "MR NORM’S",
//    "MRT",
//    "MSO",
//    "MTM",
//    "MUGEN",
//    "MULLEN",
//    "MULTIMATIC",
//    "MUNTZ",
//    "MURENA",
    
    // N
//    "NASH-HEALEY",
//    "NISMO",
    case nissan = "NISSAN"
//    "NOBLE",
//    "NOVITEC",
//    "NAPIER",
//    "NASH",
//    "NEUSPEED",
//    "NICKEY",
//    "NORMAN E. TIMBS",
//    "NOVA",
//    "NERI & BONACINI",
    
    // O
//    "OETTINGER",
//    "OLDSMOBILE",
//    "OLD YELLER",
//    "OLSBERGSMSE",
//    "OM",
//    "OPEL",
//    "ORCA",
//    "ORECA",
//    "OSCA",
//    "OSELLA",
    
    // P
//    "PACKARD",
//    "PAGANI",
//    "PANHARD",
//    "PANOZ",
//    "PEUGEOT",
//    "PIERCE-ARROW",
//    "PININFARINA",
    case plymouth = "PLYMOUTH"
    case pontiac = "PONTIAC"
    case porsche = "PORSCHE"
//    "PRODRIVE",
//    "PUMA",
//    "PPI",
//    "PGO",
//    "PEERLESS",
//    "PEGASO",
//    "PERANA",
//    "PERRIN",
//    "PESCAROLO",
//    "PICCHIO",
//    "PIERCE",
//    "PILBEAM",
//    "PIONTEK",
//    "PREMIER",
//    "PRINCE",
//    "PRINDIVILLE",
//    "PROST",
//    "PROTON",
//    "PSI",
//    "POLESTAR",
//    "PANTHER",
//    "PARRADINE",
//    "PIPER",
//    "PIRRUNG",
//    "PRATT & MILLER",
    
    // Q
//    "QUANT",
//    "QVALE",
//    "QVICK",
    
    // R
//    "RADICAL",
//    "REITER",
//    "RENAULT",
//    "RENNTECH",
//    "RILEY",
//    "RINSPEED",
//    "RMR",
//    "ROLLS-ROYCE",
//    "ROUSH",
//    "ROVER",
//    "RUF",
//    "RACING DYNAMICS",
//    "RADFORD",
//    "RE AMEMIYA",
//    "REDLINE",
//    "RENÉ BONNET",
//    "REVENGE",
//    "REYARD",
//    "REYNARD",
//    "RICKENBAKER",
    case rivian = "RIVIAN"
//    "RK COLLECTION",
//    "RLR",
//    "ROEWE",
//    "RONART",
//    "RONN MOTOR",
//    "ROOCK",
//    "ROOS",
//    "ROSSI",
//    "ROSSION",
//    "ROYAL EXCELLENCE",
//    "RSR",
//    "RTR",
//    "ROMETSCH",
//    "RUSSO-BALTIQUE",
//    "RUXTON",
//    "REZVANI",
//    "RAM",
    case rimac = "RIMAC"
//    "RANZ",
    
    // S
    case saab = "SAAB"
//    "SALEEN",
//    "SBARRO",
//    "SCARAB",
//    "SCION",
//    "SEAT",
//    "SHELBY",
//    "SINGER",
//    "SIATA",
//    "SIMCA",
//    "SMS",
//    "SPEEDART",
//    "SPORTEC",
//    "SPYKER",
//    "SSC",
//    "STARTECH",
//    "STEEDA",
//    "STOLA",
//    "STROSEK",
//    "STUTZ",
    case subaru = "SUBARU"
//    "SUNBEAM",
//    "SUPERFORMANCE",
//    "SUZUKI",
//    "SAUBER",
//    "SAAC",
//    "SADLER-MEYER",
//    "SAFIR",
//    "SAKER",
//    "SAMLSON",
//    "SANTINI",
//    "SARENI",
//    "SATURN",
//    "SAVAGE",
//    "SCG",
//    "SCHAGHTICOKE",
//    "SCHICK",
//    "SCORPION",
//    "SCUDERIA",
//    "SDR SPORTSCARS",
//    "SENSOR",
//    "SERENISSIMA",
//    "SERPOLLET",
//    "SHADOW",
//    "SIMBOL",
//    "SIMPLEX",
//    "SIZAIRE-NAUDIN",
//    "SKUNK2",
//    "SLP",
//    "SMART",
//    "SOLEIL",
//    "SOLETTA",
//    "SPADA",
//    "SPARK",
//    "SPECTER",
//    "SPECTRE",
//    "SPICE",
//    "SPIESS",
//    "SPITZER INDY",
//    "SQUIRE",
//    "S.S",
//    "STASIS",
//    "STEALTH",
//    "STEEDA",
//    "STEENSTRA",
//    "STEINMETZ",
//    "STILLEN",
//    "STING",
//    "STODDARD-DAYTON",
//    "STOVEBOLT",
//    "STRATHCARRON",
//    "STUDIE",
//    "STYLING GARAGE",
//    "SUNDOULES",
//    "SUN-RED",
//    "SUZUSHO",
//    "SWALLOW",
//    "SO-CAL",
    
    // T
//    "TALBOT",
//    "TALBOT-LAGO",
//    "TECHART",
    case tesla = "TESLA"
    case toyota = "TOYOTA"
//    "TRIDENT",
//    "TRIUMPH",
//    "TVR",
//    "TANNER FOUST",
//    "TASCA",
//    "TATRA",
//    "TATUM",
//    "TECHNICAL",
//    "TEIN",
//    "TEVERBAUGH",
//    "THOMAS FLYER",
//    "Thury-Nussberger",
//    "TIGER",
//    "TMG",
//    "TMR",
//    "TOJEIRO",
//    "TOMMY",
//    "TOM",
//    "TORAY",
//    "TOWNSEND",
//    "TRABANT",
//    "TRANSSTAR",
//    "TRD",
//    "TROUTMAN// - barnes",
//    "TUCKER",
//    "TURBO TECHNICS",
//    "TURCAT-MÉRY",
//    "Turner Motorsport",
//    "TUSHEK",
//    "TRION",
//    "TAURO SPORT",
//    "TRAMONTANA",
    
    // U
//    "ULTIMA",
//    "UNIPOWER",
    
    // V
//    "VALMET",
//    "VANDENBRINK",
//    "VAUXHALL",
//    "VDS",
//    "VECTOR",
//    "VEILSIDE",
//    "VEMAC",
//    "VENCER",
//    "VENTURI",
//    "VERITAS",
//    "VGD",
//    "VICTRESS",
//    "VIRAGO",
//    "VISION",
//    "VL-AUTOMOTIVE",
//    "VOISIN",
    case volkswagen = "VOLKSWAGEN"
    case volvo = "VOLVO"
    case vorsteiner = "VÖRSTEINER"
    case vortex = "VORTEX"
    case vuhl = "VŪHL"
    
    // W
    case wanderer = "WANDERER"
    case wcc = "WCC"
    case webb = "WEBB"
    case weber = "WEBER"
    case weineck = "WEINECK"
    case welter = "WELTER"
    case westfield = "WESTFIELD"
    case wiesmann = "WIESMANN"
    case williment = "WILLIMENT"
    case willys = "WILLYS-KNIGHT"
    
    // Y
    case yamaha = "YAMAHA"
    case yenko = "YENKO"
    case yes = "YES"
    
    // Z
    case zagato = "ZAGATO"
    case zender = "ZENDER"
    case zenos = "ZENOS"
    case zenvo = "ZENVO"
    case zytek = "ZYTEK"
    
    case other = "Other"
}

//"ABARTH",
//"ABT",
//"AC",
//"AC SCHNITZER",
//"ACURA",
//"ALFA-ROMEO",
//"ALLARD",
//"ALPINA",
//"ALPINE",
//"ALVIS",
//"AMG",
//"ARDEN",
//"ARIEL",
//"ASCARI",
//"ASTON MARTIN",
//"AUBURN",
//"AUDI",
//"AUSTIN-HEALEY",
//"AUTO UNION",
//"ARTEGA",
//"APOLLO",
//"AAC",
//"ABD",
//"ADRENALINE",
//"AEON",
//"ALAN MANN",
//"ALBA",
//"AMERICAN MOTORS",
//"AMILCAR",
//"ARCH",
//"ARK",
//"ARASH",
//"ASC",
//"ASL",
//"ASMA",
//"ATS",
//"AUBURN",
//"AUSTIN",
//"AUTECH",
//"BAC",
//"BALDWIN MOTION",
//"BERTONE",
//"BALLOT",
//"BENTLEY",
//"BENZ",
//"BIZZARRINI",
//"BMW",
//"BRABUS",
//"BUGATTI",
//"BUICK",
//"CADILLAC",
//"CALLAWAY",
//"CARLSSON",
//"CATERHAM",
//"CHEVROLET",
//"CHRYSLER",
//"CITROËN",
//"CISITALIA",
//"CHEVRON",
//"CASTAGNA",
//"CIZETA",
//"CAPARO",
//"CONTINENTAL",
//"COOPER",
//"CORD",
//"CORVAIR",
//"COURAGE",
//"DAIMLER",
//"DATSUN",
//"DAUER",
//"DELAGE",
//"DELAHAYE",
//"DETOMASO",
//"DINO",
//"DODGE",
//"DOME",
//"DONKERVOORT",
//"DUESENBERG",
//"DACIA",
//"DAEWOO",
//"DAIHATSU",
//"DE DION-BOUTON",
//"DELAUNAY",
//"DELOREAN",
//"DENZEL",
//"DERBY",
//"DESOTO",
//"DETROIT ELECTRIC",
//"DEVIN",
//"DEVON",
//"DIATTO",
//"DINAN",
//"DKW",
//"DORAN",
//"DP",
//"DREKER",
//"DUAL-GHIA",
//"DUPONT",
//"DAVID BROWN",
//"DEVEL SIXTEEN",
//"EDAG",
//"EDO",
//"EDWARDS",
//"ELFIN",
//"ELVA",
//"EAGLE",
//"ECHIDNA",
//"EMME",
//"ENIZIO",
//"EPSILON",
//"ERMINI",
//"ETUD",
//"EUNOS",
//"EVANS",
//"EVOLVE",
//"EXAGON",
//"ELEMENTAL",
//"FERRARI",
//"FIAT",
//"FIORAVANTI",
//"FISKER",
//"FORD",
//"FABCAR",
//"FACEL VEGA",
//"9FF",
//"FARADAY",
//"FIFTEEN52",
//"FLAJOLE",
//"FOOSE",
//"FORCED FED",
//"FACETTI",
//"FACTORY FIVE",
//"FARALLI & MAZZ..",
//"FARBIO",
//"FARMAN",
//"FARBOUD",
//"FENIX",
//"FAB DESIGN",
//"FENOMENON",
//"FRAZER NASH",
//"FRONTY",
//"F.R.P",
//"FSWERKS",
//"FUORE",
//"GALPIN",
//"GEIGER",
//"GEMBALLA",
//"GHIA",
//"GINETTA",
//"GENERAL MOTORS",
//"GORDINI",
//"GPOWER",
//"GREENWOOD",
//"GRMN",
//"GUMPERT",
//"GAACO",
//"GEELY",
//"GENADDI",
//"GIGLIATO",
//"GILLET",
//"GIUGIARO",
//"GLASSPAR",
//"GRABER CARS",
//"GREDDY",
//"GTA",
//"GENESIS",
//"GILLET",
//"GMC",
//"HAMANN",
//"HARLEY-DAVIDSON",
//"HARTGE",
//"HENNESSEY",
//"HISPANO-SUIZA",
//"HOLDEN",
//"HONDA",
//"HOMMEL",
//"HORCH",
//"HPD",
//"HSV",
//"HURST",
//"HONGQI",
//"HAFEI",
//"HASPORT",
//"HBH",
//"HEYNSDYK",
//"HKS",
//"HUNTER",
//"HOERMANN",
//"HOOPER",
//"HOTCHKISS",
//"HOWELL",
//"HRG",
//"HUDSON",
//"HULME",
//
//"HYUNDAI",
//"HEULIEZ",
//"IMPERIAL",
//"INDIAN",
//"INFINITI",
//"INNOTECH",
//"ISDERA",
//"ISO",
//"ISOTTA",
//"ISUZU",
//"ITALDESIGN",
//"I.DE.A",
//"IED",
//"IMOLA RACING",
//"IMPUL",
//"IMSA",
//"INTERMECCANICA",
//"INTREPID",
//"INVICTA",
//"ICENI",
//"ICONA",
//"ICONIC",
//"ITALMECCANICA",
//"JAGUAR",
//"JEEP",
//"JENSEN",
//"JAVAN",
//"JETSTREAM",
//"JIMENEZ",
//"JIOTTO",
//"JOEST",
//"JBA",
//"JAC",
//"KAISER-DARRIN",
//"KARMANN",
//"KATECH",
//"KEATING",
//"KELLISON",
//"KEPLER MOTORS",
//"KIA",
//"KICHERER",
//"KLEEMANN",
//"KOENIGSEGG",
//"KOENIG-SPECIALS",
//"KREMER",
//"KTM",
//"KURTIS",
//"KARMA",
//"KAWASAKI",
//"LAGONDA",
//"LAMBORGHINI",
//"LANCIA",
//"LEXUS",
//"LINCOLN",
//"LINGENFELTER",
//"LISTER",
//"LOLA",
//"LOTUS",
//"LABORATORIO",
//"LANCHESTER",
//"LAND ROVER",
//"LANG-COOPER",
//"LARAKI",
//"LASALLE",
//"Laurin & Klement",
//"LEA FRANCIS",
//"LEBLANC",
//"LIGHTNING",
//"LIGIER",
//"LJ GARCIA",
//"LOCAL MOTORS",
//"LOCOMOBILE",
//"LOCUS",
//"LODER1899",
//"LOHNER-PORSCHE",
//"LOREMO",
//"LORRAINE DIE..",
//"LOTEC",
//"LUMMA,",
//"LYKAN",
//"LLOYD",
//"LOBINI",
//"LUCID",
//"LUXGEN",
//"MAGNA",
//"MALLETT",
//"MAMEROW",
//"MANSORY",
//"MARCH",
//"MARCOS",
//"MARMON",
//"MARUSSIA",
//"MASERATI",
//"MASTRETTA",
//"MATECH-FORD",
//"MATRA-SIMCA",
//"MAYBACH",
//"MAZDA",
//"MAZEL",
//"MAZZANTI",
//"MCA",
//"MCCULLOCH",
//"MCLAREN",
//"MCV",
//"MEGA",
//"MELKUS",
//"MELLING",
//"MERCEDES",
//"MERCEDES-AMG",
//"MERCEDES-BENZ",
//"MERCEDES-KNIGHT",
//"MERCER",
//"MERCURY",
//"MG",
//"MILLER",
//"MINERVA",
//"MINI",
//"MIRAGE",
//"MITSUBISHI",
//"MITSUOKA",
//"MOBSTEEL",
//"MOMO",
//"MONTEVERDI",
//"MOONCRAFT",
//"MORETTI",
//"MORGAN",
//"MORRIS",
//"MOSLER",
//"MR NORM’S",
//"MRT",
//"MSO",
//"MTM",
//"MUGEN",
//"MULLEN",
//"MULTIMATIC",
//"MUNTZ",
//"MURENA",
//"NASH-HEALEY",
//"NISMO",
//"NISSAN",
//"NOBLE",
//"NOVITEC",
//"NAPIER",
//"NASH",
//"NEUSPEED",
//"NICKEY",
//"NORMAN E. TIMBS",
//"NOVA",
//"NERI & BONACINI",
//"OETTINGER",
//"OLDSMOBILE",
//"OLD YELLER",
//"OLSBERGSMSE",
//"OM",
//"OPEL",
//"ORCA",
//"ORECA",
//"OSCA",
//"OSELLA",
//"PACKARD",
//"PAGANI",
//"PANHARD",
//"PANOZ",
//"PEUGEOT",
//"PIERCE-ARROW",
//"PININFARINA",
//"PLYMOUTH",
//"PONTIAC",
//"PORSCHE",
//"PRODRIVE",
//"PUMA",
//"PPI",
//"PGO",
//"PEERLESS",
//"PEGASO",
//"PERANA",
//"PERRIN",
//"PESCAROLO",
//"PICCHIO",
//"PIERCE",
//"PILBEAM",
//"PIONTEK",
//"PREMIER",
//"PRINCE",
//"PRINDIVILLE",
//"PROST",
//"PROTON",
//"PSI",
//"POLESTAR",
//"PANTHER",
//"PARRADINE",
//"PIPER",
//"PIRRUNG",
//"PRATT & MILLER",
//"QUANT",
//"QVALE",
//"QVICK",
//"RADICAL",
//"REITER",
//"RENAULT",
//"RENNTECH",
//"RILEY",
//"RINSPEED",
//"RMR",
//"ROLLS-ROYCE",
//"ROUSH",
//"ROVER",
//"RUF",
//"RACING DYNAMICS",
//"RADFORD",
//"RE AMEMIYA",
//"REDLINE",
//"RENÉ BONNET",
//"REVENGE",
//"REYARD",
//"REYNARD",
//"RICKENBAKER",
//"RK COLLECTION",
//"RLR",
//"ROEWE",
//"RONART",
//"RONN MOTOR",
//"ROOCK",
//"ROOS",
//"ROSSI",
//"ROSSION",
//"ROYAL ENFIELD",
//"ROYAL EXCELLENCE",
//"RSR",
//"RTR",
//"ROMETSCH",
//"RUSSO-BALTIQUE",
//"RUXTON",
//"REZVANI",
//"RAM",
//"RIMAC",
//"RANZ",
//"SAAB",
//"SALEEN",
//"SBARRO",
//"SCARAB",
//"SCION",
//"SEAT",
//"SHELBY",
//"SINGER",
//"SIATA",
//"SIMCA",
//"SMS",
//"SPEEDART",
//"SPORTEC",
//"SPYKER",
//"SSC",
//"STARTECH",
//"STEEDA",
//"STOLA",
//"STROSEK",
//"STUTZ",
//"SUBARU",
//"SUNBEAM",
//"SUPERFORMANCE",
//"SUZUKI",
//"SAUBER",
//"SAAC",
//"SADLER-MEYER",
//"SAFIR",
//"SAKER",
//"SAMLSON",
//"SANTINI",
//"SARENI",
//"SATURN",
//"SAVAGE",
//"SCG",
//"SCHAGHTICOKE",
//"SCHICK",
//"SCORPION",
//"SCUDERIA",
//"SDR SPORTSCARS",
//"SENSOR",
//"SERENISSIMA",
//"SERPOLLET",
//"SHADOW",
//"SIMBOL",
//"SIMPLEX",
//"SIZAIRE-NAUDIN",
//"SKUNK2",
//"SLP",
//"SMART",
//"SOLEIL",
//"SOLETTA",
//"SPADA",
//"SPARK",
//"SPECTER",
//"SPECTRE",
//"SPICE",
//"SPIESS",
//"SPITZER INDY",
//"SQUIRE",
//"S.S",
//"STASIS",
//"STEALTH",
//"STEEDA",
//"STEENSTRA",
//"STEINMETZ",
//"STILLEN",
//"STING",
//"STODDARD-DAYTON",
//"STOVEBOLT",
//"STRATHCARRON",
//"STUDIE",
//"STYLING GARAGE",
//"SUNDOULES",
//"SUN-RED",
//"SUZUSHO",
//"SWALLOW",
//"SO-CAL",
//"TALBOT",
//"TALBOT-LAGO",
//"TECHART",
//"TESLA",
//"TOYOTA",
//"TRIDENT",
//"TRIUMPH",
//"TVR",
//"TANNER FOUST",
//"TASCA",
//"TATRA",
//"TATUM",
//"TECHNICAL",
//"TEIN",
//"TEVERBAUGH",
//"THOMAS FLYER",
//"Thury-Nussberger",
//"TIGER",
//"TMG",
//"TMR",
//"TOJEIRO",
//"TOMMY",
//"TOM",
//"TORAY",
//"TOWNSEND",
//"TRABANT",
//"TRANSSTAR",
//"TRD",
//"TROUTMAN// - barnes",
//"TUCKER",
//"TURBO TECHNICS",
//"TURCAT-MÉRY",
//"Turner Motorsport",
//"TUSHEK",
//"TRION",
//"TAURO SPORT",
//"TRAMONTANA",
//"ULTIMA",
//"UNIPOWER",
//"VALMET",
//"VANDENBRINK",
//"VAUXHALL",
//"VDS",
//"VECTOR",
//"VEILSIDE",
//"VEMAC",
//"VENCER",
//"VENTURI",
//"VERITAS",
//"VGD",
//"VICTRESS",
//"VIRAGO",
//"VISION",
//"VL-AUTOMOTIVE",
//"VOISIN",
//"VOLKSWAGEN",
//"VOLVO",
//"VÖRSTEINER",
//"VORTEX",
//"VŪHL",
//"WANDERER",
//"WCC",
//"WEBB",
//"WEBER",
//"WEINECK",
//"WELTER",
//"WESTFIELD",
//"WIESMANN",
//"WILLIMENT",
//"WILLYS-KNIGHT",
//"YAMAHA",
//"YENKO",
//"YES",
//"ZAGATO",
//"ZENDER",
//"ZENOS",
//"ZENVO",
//"ZYTEK",
